name: Client pipe

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build
        working-directory: ./client
        run: npm run build
      
      - name: Get SSH key and set permissions
        working-directory: ./client
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ssh_key
      

